### ISSUE TITLE
Generate bindings at crate publishing time

### ISSUE THREAD

**Issue by jrmuizel** [jamienicol/glslopt-rs#2]
This would let us drop the bindgen dependency which can be pain when compiling WebRender standalone.

**Comment by jamienicol** [comment]
Couldn't figure out a way to do it at publishing time. And doing so would mean you can't use it with `glsloptrs = { git = "", rev = "" }` which might make testing fixes a bit trickier? So I've just checked in the bindings, and we'll hopefully always remember to update it.
