### ISSUE TITLE
Fix build on OpenBSD

### ISSUE THREAD

**Issue by landryb** [jamienicol/glslopt-rs#7]
As suggested in #5, `<pthread_np.h>` is needed on OpenBSD to access `pthread_set_name_np()` method. As of now, the build of firefox 81.0b1 fails on this, my hackish workaround was to add openbsd to the test for PTHREAD_SETAFFINITY_IN_NP_HEADER but i dunno if it's the best fix.

eg
```
@@ -8,7 +8,7 @@ fn configure(build: &mut cc::Build) -> &mut cc::Build 
         build.define("_GNU_SOURCE", None);
         build.define("HAVE_ENDIAN_H", None);
     }
-    if cfg!(any(target_os = "freebsd", target_os = "dragonfly")) {
+    if cfg!(any(target_os = "freebsd", target_os = "dragonfly", target_os = "openbsd")) {
         build.define("PTHREAD_SETAFFINITY_IN_NP_HEADER", None);
     }
     if cfg!(target_os = "windows") {
```

Will file a bug on bmo for the uplift

**Comment by landryb** [comment]
cf https://bugzilla.mozilla.org/show_bug.cgi?id=1661045

**Comment by jamienicol** [comment]
Thanks for filing the bug @landryb . To confirm, you were able to build gecko successfully after making the above change? If so, I'll go ahead and land it.

**Comment by landryb** [comment]
still fighting a bit with .cargo-checksum.json files not liking me modifying build.rs behind its back, but it should be fine... dunno if you want a different define has it has nothing to do with pthread_setaffinity() (which we dont have)

**Comment by jamienicol** [comment]
Yeah, it feels wrong to use that macro to fix set_name, when it wouldn't be defined Mesa's build system because as you say there's no setaffinity. However, I'm trying to avoid making changes to mesa files where possible. I'm confused about how set_name works in Mesa on OpenBSD!

**Comment by jamienicol** [comment]
For the cargo-checksum issue, you can create a glslopt-rs clone, make the change and push your branch to github. Then in gfx/wr/webrender/Cargo.toml change the `glslopt = "0.1.6"` line to `glslopt = { git = "https://github.com/landryb/glslopt-rs", branch = "openbsd" }`. Then run `./mach vendor rust` in the root gecko dir.

It's quite awkward and there might be an easier way, but that should work.

**Comment by landryb** [comment]
in the end, there were quite a lot of warnings in the glslopt crate build, but my build of 81.0b1 is now past it (not completely over yet), so my workaround works. Can of course test any other better suggestion :)

**Comment by jamienicol** [comment]
Okay, well it remains a mystery how this works in mesa, but I've decided just to define it for OpenBSD too. Thanks!
